

<div class="inner cover">
    <?php if($this->mensagem_erro!= ""): ?>
    <div class="alert alert-warning" role="alert"><?php echo $this->mensagem_erro ?></div>
    <?php endif;?>
    <h1>Cadastrar</h1>
    <div class="row">
        <form action="<?php echo $this->baseUrl(); ?>/index/cadastrar" method="post">
            <div class="col-xs-6">
                <div class="form-group">
                    <label>Nome completo</label>
                    <input name="nome" type="text" class="form-control"  placeholder="Nome Completo">
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    <label>Escolha um nome de usuário</label>
                    <input name="usuario" type="text" class="form-control"  placeholder="Usuário">
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    <label>Email</label>
                    <input name="email" type="text" class="form-control"  placeholder="Email">
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    <label>Senha</label>
                    <input name="senha" type="password" class="form-control"  placeholder="senha">
                </div>
            </div>
            <div class="col-xs-12">
                <div class="row text-right">
                    <div class="col-xs-12 ">
                        <div class="form-group">
                            <a class="btn btn-default" href="<?php echo $this->baseUrl();?>/">Voltar</a>
                            <button class="btn btn-primary" type="submit">Cadastrar</button>
                        </div>
                    </div>

                </div>


            </div>
        </form>

        <div class="mastfoot">
            <div class="inner">
                <p>HolySolutions <a href="http://www.holysolutions.com.br/">Site</a>
            </div>
        </div>

    </div>

</div>

