

<div class="inner cover">
    <h1 class="cover-heading">Gerencie seu grupo.</h1>
    <p class="lead">Gerencie seu grupo de louvor ou ministerio com SongController.</p>
    <p class="lead">Faça o cadastro e começe a usar.</p>
    <p class="lead">
        <a href="<?php echo $this->baseUrl(); ?>/index/cadastrar" class="btn btn-lg btn-default">Cadastrar</a>
    </p>
</div>

<div class="mastfoot">
    <div class="inner">
        <p>HolySolutions <a href="http://www.holysolutions.com.br/">Site</a>
    </div>
</div>

