<!DOCTYPE html>
<html lang="en" class="body-full-height">
    <head>        
        <!-- META SECTION -->
        <title>Song Controller | Login</title>            
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="favicon.ico" type="image/x-icon" />
        <!-- END META SECTION -->

        <!-- CSS INCLUDE -->        
        <link rel="stylesheet" type="text/css" id="theme" href="<?php echo $this->baseUrl() ?>/joli/css/theme-default.css"/>
        <!-- EOF CSS INCLUDE -->                                     
    </head>
    <body>

        <div class="login-container lightmode">

            <div class="login-box animated fadeInDown">
                <h1 style="color: #f4f4f4 ; font-family: sans-serif; text-align: center"><strong>SongController</strong></h1>
                <?php if ($this->mensagem_erro != ""): ?>
                <div class="alert alert-danger" role="alert"><strong><?php echo $this->mensagem_erro ?></strong></div>
                <?php endif; ?>
                <?php if ($this->mensagem_aviso != ""): ?>
                    <div class="alert alert-success" role="alert"><strong><?php echo $this->mensagem_aviso ?></strong></div>
                <?php endif; ?>
                <div class="login-body">
                    <div class="login-title"><strong>Log In</strong> para sua conta</div>
                    <form action="<?php echo $this->baseUrl(); ?>/index/login" class="form-horizontal" method="post">
                        <div class="form-group">
                            <div class="col-md-12">
                                <input name="usuario" type="text" class="form-control" placeholder="Usuário" required value="<?php echo isset($_COOKIE['usuario']) ? $_COOKIE['usuario'] : "" ?>"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <input name="senha" type="password" class="form-control" placeholder="Senha" required value="<?php echo isset($_COOKIE['senha']) ? $_COOKIE['senha'] : "" ?>"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4">
                                <label>
                                    <input name="lembrar" type="checkbox" value="remember-me"> Lembrar-me
                                </label>
                            </div>
                            <div class="col-md-4">
                                <a href="<?php echo $this->baseUrl() ?>" class="btn btn-primary btn-block">Voltar </a>
                            </div>
                            <div class="col-md-4">
                                <button name="logar" type="submit" class="btn btn-info btn-block">Entrar</button>
                            </div>
                        </div>
                        <div class="checkbox">

                        </div>
                    </form>
                </div>
                <div class="login-footer">
                    <div class="pull-left">
                        &copy; 2016 SongController
                    </div>
                </div>
            </div>

        </div>

    </body>
</html>






