<div class="col-md-12">


    <div class="page-title">
        <div class="col-xs-6">
            <h2><span class="fa fa-calendar"></span><span class="xn-text"></span>  <u>Cultos</u></h2>
        </div>
        <div class="col-md-6 text-right">
            <?php if (Integrante::getLogged()->tipo == Integrante::TIPO_ADMINISTRADOR): ?>
                <a class="btn btn-success btn-lg" href="<?php echo $this->baseUrl(); ?>/administrador/culto/novo"><span class="glyphicon glyphicon-plus"></span>Novo</a>
            <?php endif; ?>
        </div>
    </div>



    <?php if ($this->mensagem_aviso != ""): ?>
        <div class="alert alert-success" role="alert"><strong><?php echo $this->mensagem_aviso; ?></strong></div>
    <?php endif; ?>



    <form class="form-group" action="<?php echo $this->baseUrl() ?>/administrador/culto" method="GET">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-4">
                        <div class="form-group">
                            <label>Nome</label>
                            <input name="nome" type="text" class="form-control"  placeholder="Nome do Culto" style="text-transform: capitalize" value="<?php echo $this->params['nome'] ?>">
                        </div>
                    </div>
                    <div class="col-xs-3">
                        <div class="form-group" >
                            <label>Data</label>
                            <input name="data" type="date" class="form-control" >
                        </div>
                    </div>
                    <div class="col-xs-2">
                        <div class="form-group" >
                            <label>Hora</label>
                            <input name="hora" type="time" class="form-control" >
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="form-group" style="text-align: right">
                        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-filter" ></span>Filtrar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div class="panel panel-default">
        <div class="panel-heading ui-draggable-handle">
            <h3>Lista de Músicas</h3>
        </div>
        <table class="table table-hover ">
            <thead class="tabela-header">
                <tr>
                    <th>Nome</th>
                    <th>Data</th>
                    <th>Hora</th>


                    <th colspan="3"></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->lista_cultos as $culto): ?>
                    <tr>
                        <td><strong><?php echo $culto->nome ?></strong></td>
                        <td><strong><?php echo date('d/m/Y', strtotime($culto->data)) ?></strong></td>
                        <td><strong><?php echo substr($culto->hora, 0, 5) ?></strong></td>


                        <td><a class="glyphicon glyphicon-eye-open" href="<?php echo $this->baseUrl() ?>/administrador/culto/visualizar?id=<?php echo $culto->id ?>" title="Visualizar" ></a></td>

                        <?php if (Integrante::getLogged()->tipo == Integrante::TIPO_ADMINISTRADOR): ?>
                            <td><a class="glyphicon glyphicon-pencil" title="Editar" href="<?php $this->baseUrl() ?>/administrador/culto/editar?id=<?php echo $culto->id ?>"></a></td>
                        <?php endif; ?>
                        <?php if (Integrante::getLogged()->tipo == Integrante::TIPO_ADMINISTRADOR): ?>
                            <td><a onclick="return confirm('Confirma exclusão desse integrante ? ')" class="glyphicon glyphicon-trash" title="Excluir" href="<?php $this->baseUrl() ?>/administrador/culto/deletar?id=<?php echo $culto->id ?>"></a></td>
                            <?php endif; ?>
                    </tr>

                <?php endforeach; ?>

            </tbody>
        </table>
    </div>



    <?php if (isset($this->lista_cultos)) echo $this->paginationControl($this->lista_cultos, "All", "paginator.phtml", $this->list_params); ?>

</div>
