<div class="col-md-12">


    <div class="page-title">
        <h2><u>Cadastro de Culto</u></h2>
    </div>
    <?php if ($this->mensagem_erro != ""): ?>
        <div class="alert alert-warning" role="alert"><strong><?php echo $this->mensagem_erro; ?></strong></div>
    <?php endif; ?>


    <form action="<?php $this->baseUrl(); ?>/administrador/culto/novo" method="post" enctype="multipart/form-data" >
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-6">
                        <div class="form-group">
                            <label>Nome</label>
                            <input  name="nome" type="text" class="form-control"  placeholder="Nome do culto" value="<?php echo $this->culto->nome ?>">
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="form-group">
                            <label>Local</label>
                            <input  name="local" type="text" class="form-control"  placeholder="local" value="<?php echo $this->culto->local ?>">
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="form-group">
                            <label>Data</label>
                            <input  name="data" type="date" class="form-control" value="<?php echo $this->culto->data ?>">
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="form-group">
                            <label>Hora</label>
                            <input name="hora" type="time" class="form-control" value="<?php echo $this->culto->hora ?>">
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-striped">
                    <div class="col-md-6">
                        <h3><strong>Escala do culto</strong></h3>
                    </div>
                    <thead>
                        <tr>
                            <th style="text-align: center">Instrumento</th>
                            <th style="text-align: center">Integrante</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->instrumentos as $instrumento): ?>
                            <tr>
                                <td> 
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <input name="instrumento[]" type="hidden" value="<?php echo $instrumento->id ?>">
                                            <p><strong><?php echo $instrumento->nome ?></strong></p>
                                        </div>
                                    </div>
                                </td>
                                <td> 

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <select name="integrante[]" class="form-control select">
                                                <option value="0">[Selecione o integrante]</option>
                                                <?php foreach ($instrumento->IntegranteInstrumento as $integrante_instrumento): ?>
                                                    <option value="<?php echo $integrante_instrumento->Integrante->id ?>"><?php echo $integrante_instrumento->Integrante->nome ?></option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <table class="table table-striped">
                    <div class="col-md-6">
                        <h3><strong>Repertório de músicas</strong></h3>
                    </div>
                    <thead>
                        <tr>
                            <th style="text-align: center"></th>
                            <th style="text-align: center">Músicas</th>
                            <th style="text-align: center">Arquivos</th>
                        </tr>
                    </thead>
                    <tbody id="tabela">
                        <?php foreach ($this->musicas as $musica): ?>
                            <tr id="linha">
                                <td style="text-align: center"  > 
                                    <input name="musica[]" type="checkbox" value="<?php echo $musica->id ?>">
                                </td>
                                <td style="text-align: center"> 
                                    <?php echo $musica->nome ?>
                                </td>
                                <td style="text-align: center">
                                    <div class="dropdown">
                                        <a class="glyphicon glyphicon-folder-open" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></a>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                            <?php if ($musica->letra != ""): ?>
                                                <li><a href="<?php echo $this->baseUrl() ?>/uploads/letra/<?php echo $musica->letra ?>" target="_blank">Arquivo Letra</a></li>
                                            <?php endif; ?>
                                            <?php if ($musica->cifra != ""): ?>
                                                <li><a href="<?php echo $this->baseUrl() ?>/uploads/cifra/<?php echo $musica->cifra ?>" target="_blank">Arquivo Cifra</a></li>
                                            <?php endif; ?>
                                            <?php if ($musica->link != ""): ?>
                                                <li><a href="<?php echo $musica->link ?>" target="_blank">Link Musica</a></li>
                                            <?php endif; ?>
                                            <li role="separator" class="divider"></li>
                                            <?php if ($musica->power_point != ""): ?>
                                                <li><a href="<?php echo $this->baseUrl() ?>/uploads/powerpoints/<?php echo $musica->power_point ?>" download >Baixar e Editar Power Point</a></li>
                                            <?php endif; ?>
                                            <?php if ($musica->cifra != ""): ?>
                                                <li><a href="<?php echo $this->baseUrl() ?>/uploads/cifra/<?php echo $musica->cifra ?>" download >Baixar e Editar Cifra</a></li>
                                            <?php endif; ?>
                                            <?php if ($musica->arquivo_mp3 != ""): ?>
                                                <li><a href="<?php echo $this->baseUrl() ?>/uploads/mp3/<?php echo $musica->arquivo_mp3 ?>" download >Baixar Música</a></li>
                                            <?php endif; ?>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div class="row text-right">
                <div class="col-xs-12 ">
                    <div class="form-group" >
                        <a class="btn btn-default btn-lg" href="<?php echo $this->baseUrl() ?>/administrador/culto">Cancelar</a>
                        <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
                    </div>
                </div>

            </div>
        </div>
</div>
</form>

</div>
<!--<script>
    function clonarLinha() {
        var row = document.getElementById("linha");
        var table = document.getElementById("tabela");
        var clone = row.cloneNode(true);
        clone.id = "linhaClonada";
        table.appendChild(clone);
    }
</script>-->