<div class="col-md-12">


    <div class="page-title">
        <div class="col-xs-6">
            <h1><span class="fa fa-desktop"></span><span class="xn-text"></span>  <u>Grupos</u></h1>
        </div>
        <!--<div class="col-md-6 text-right">
        <a class="btn btn-success" href="<?php echo $this->baseUrl(); ?>/administrador/grupo/novo"><span class="glyphicon glyphicon-plus"></span>Novo</a>
    </div>-->
    </div>



    <?php if ($this->mensagem_aviso != ""): ?>
        <div class="alert alert-success" role="alert"><?php echo $this->mensagem_aviso; ?></div>
    <?php endif; ?>



    <form class="form-group" action="<?php echo $this->baseUrl() ?>/administrador/grupo" method="GET">
        <div class="panel panel-default" >
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-5">
                        <div class="form-group">
                            <label>Nome do grupo</label>
                            <input name="nome" type="text" class="form-control"  placeholder="Nome do grupo" value="<?php echo $this->params['nome'] ?>">
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="form-group" style="text-align: right">
                        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-filter"></span>Filtrar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div class="panel panel-default">
        <div class="panel-heading ui-draggable-handle">
            <h3>Lista de Grupos</h3>
        </div>
        <table class="table table-hover ">
            <thead>
                <tr>
                    <th>Grupo</th>
                    <th>Igreja</th>
                    <th>Resposável</th>
                    <th colspan="2"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->lista_grupos as $lista_grupo): ?>
                    <tr>
                        <td><strong><?php echo $lista_grupo->nome ?></strong></td>
                        <td><strong><?php echo $lista_grupo->igreja ?></strong></td>
                        <td><strong><?php echo $lista_grupo->responsavel ?></strong></td>
                        <td><a class="fa fa-pencil" href="<?php echo $this->baseUrl() ?>/administrador/grupo/editar?id=<?php echo $lista_grupo->id ?>"></a></td>
                        <td><a onclick="return confirm('Confirma a exclusão do grupo ? ')" class="glyphicon glyphicon-trash" href="<?php echo $this->baseUrl() ?>/administrador/grupo/deletar?id=<?php echo $lista_grupo->id ?>"></a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?php if (isset($this->lista_grupos)) echo $this->paginationControl($this->lista_grupos, "All", "paginator.phtml", $this->list_params); ?>

</div>