<div class="col-md-12">
    <div class="page-title">
        <?php if ($this->mensagem_erro != ""): ?>
            <div class="alert alert-warning" role="alert"><strong><?php echo $this->mensagem_erro; ?></strong></div>
        <?php endif; ?>
        <div class="page-title">
            <h2>Cadastro de Grupos</h2>
        </div>
    </div>



    <div class="row">
        <form action="<?php $this->baseUrl() ?>/administrador/grupo/novo" method="post" enctype="multipart/form-data">
            <div class="col-xs-6">
                <div class="form-group">
                    <label>Nome do grupo</label>
                    <input name="grupo" type="text" class="form-control" placeholder="Nome do grupo" value="<?php echo $this->grupo->nome ?>" style="text-transform: capitalize;">
                </div>
            </div>

            <div class="col-xs-6">
                <div class="form-group">
                    <label>Nome do Responsável</label>
                    <input name="responsavel" type="text" class="form-control" placeholder="Responsável" value="<?php echo $this->grupo->responsavel ?>" style="text-transform: capitalize;">
                </div>
            </div>

            <div class="col-xs-6">
                <div class="form-group">
                    <label>Nome da Igreja</label>
                    <input name="igreja" type="text" class="form-control" placeholder="Igreja"<?php echo $this->grupo->igreja ?> style="text-transform: capitalize;">
                </div>
            </div>

            <div class="col-xs-6">
                <div class="form-group">
                    <label for="exampleInputFile">Escolha foto do Grupo</label>
                    <input name="imagem" type="file" id="exampleInputFile">
                </div>
            </div>

            <div class="row text-right">
                <div class="col-xs-12 ">
                    <div class="form-group" style="margin: 20px 25px">
                            <a class="btn btn-default btn-lg" href="<?php echo $this->baseUrl() ?>/administrador/grupo">Cancelar</a>
                            <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
                        </div>
                </div>

            </div>
        </form>
    </div>
</div>