<div class="col-md-12">


    <div class="page-title">
        <h2>Cadastro Instrumentos</h2>
    </div>

    <?php if ($this->mensagem_erro != ""): ?>
        <div class="alert alert-warning" role="alert"><strong><?php echo $this->mensagem_erro ?></strong></div>
    <?php endif; ?>



    <form action="<?php $this->baseUrl() ?>/administrador/instrumento/novo" method="post">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-6">
                        <div class="form-group">
                            <label>Nome do instrumento</label>
                            <input name="nome" type="text" class="form-control"  placeholder="Nome do instrumento" style="text-transform: capitalize;" value="<?php echo $this->instrumento->nome ?>">
                        </div>
                    </div>

                    <div class="col-xs-4">
                        <div class="form-group">
                            <label>Selecione a situação</label>
                            <select name="situacao" class="form-control select">
                                <option value="<?php echo Instrumento::SITUACAO_OTIMO ?>">Otimo</option>
                                <option value="<?php echo Instrumento::SITUACAO_BOM ?>">Bom</option>
                                <option value="<?php echo Instrumento::SITUACAO_REGULAR ?>">Regular</option>
                                <option value="<?php echo Instrumento::SITUACAO_RUIM ?>">Ruim</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <label>Vinculado à: </label>
                        <div class="form-group">
                            <?php foreach ($this->lista_integrantes as $integrante): ?>
                                <div class="col-xs-6">
                                    <label class="checkbox-inline">
                                        <input name="vinculo[]" type="checkbox" id="inlineCheckbox1" value="<?php echo $integrante->id ?>"> <strong><?php echo $integrante->nome ?></strong>
                                    </label>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="form-group">
                            <label>Selecione o status</label>
                            <select name="status" class="form-control select">
                                <option value="<?php echo Instrumento::STATUS_ATIVO ?>">Ativo</option>
                                <option value="<?php echo Instrumento::STATUS_INATIVO ?>">Inativo</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="row text-right">
                    <div class="col-xs-12 ">
                        <div class="form-group" >
                            <a class="btn btn-default btn-lg" href="<?php echo $this->baseUrl() ?>/administrador/instrumento">Cancelar</a>
                            <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </form>

</div>