

<form  class="form-group" action="" method="post" enctype="multipart/form-data">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-3">
                    <div class="form-group">

                        <div class="btn btn-toolbar btn-file ">
                            <span>
                                <?php if ($this->integrante->foto != "") { ?>
                                    <img width="140" height="140" src="<?php echo $this->baseUrl() ?>/uploads/fotointegrante/<?php echo $this->integrante->foto ?>" alt="Foto" class="img-circle" >
                                <?php } else { ?>
                                    <img width="140" height="140" src="<?php echo $this->baseUrl() ?>/uploads/fotointegrante/default-user.jpg" alt="Foto" class="img-circle" >
                                <?php } ?>
                                <input  name="foto" type="file" multiple="" class="file" data-preview-file-type="any" id="1465570570208" >                                 
                            </span>
                        </div>
                    </div>
                    <label for="1465570570208" title="Clique para editar foto de perfil" style="margin-left: 33px; cursor: pointer" class="btn  btn-primary"><strong>Editar Foto</strong></label>
                </div>

                <div class="col-xs-5">
                    <div class="form-group">
                        <label>Nome do integrante</label>
                        <input name="nome" type="text" class="form-control"  placeholder="integrante" value="<?php echo $this->integrante->nome ?>">
                    </div>

                    <div class="form-group">
                        <label>Usuário</label>
                        <input name="usuario" type="text" class="form-control"  placeholder="usuário" value="<?php echo $this->integrante->usuario ?>">
                    </div>

                    <div class="form-group">
                        <label>Senha</label>
                        <?php if ($this->integrante->senha != ""): ?>
                            <input name="senha" class="form-control" id="disabledInput" type="password" value="<?php echo $this->integrante->senha ?>" >
                        <?php endif; ?>
                        <?php if ($this->integrante->senha == ""): ?>
                            <input name="senha" class="form-control" id="disabledInput" type="text" value="<?php echo rand(100000, 800000); ?>" readonly>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="col-xs-4">
                    <div class="form-group">
                        <label>Selecione a categoria</label>
                        <select name="categoria" class="form-control select">
                            <option value="<?php echo Integrante::CATEGORIA_CANTOR ?>" <?php echo Integrante::CATEGORIA_CANTOR == $this->integrante->categoria ? 'selected' : '' ?> >Cantor</option>
                            <option value="<?php echo Integrante::CATEGORIA_MUSICO ?>" <?php echo Integrante::CATEGORIA_MUSICO == $this->integrante->categoria ? 'selected' : '' ?>>Músico</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input name="email" type="text" class="form-control"  placeholder="email" value="<?php echo $this->integrante->email ?>">
                    </div>
                    <div class="form-group">
                        <label>Selecione o status</label>
                        <select name="status" class="form-control select">
                            <option value="<?php echo Integrante::STATUS_ATIVO ?>" <?php echo Integrante::STATUS_ATIVO == $this->integrante->status ? 'selected' : '' ?> >Ativo</option>
                            <option value="<?php echo Integrante::STATUS_INATIVO ?>" <?php echo Integrante::STATUS_INATIVO == $this->integrante->status ? 'selected' : '' ?> >Inativo</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <div class="row text-right">
                <div class="col-xs-12 ">
                    <div class="form-group" >
                        <a class="btn btn-default btn-lg" href="<?php echo $this->baseUrl() ?>/administrador/integrante">Cancelar</a>
                        <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

