<div class="col-md-12">

    <div class="page-title">
        <div class="col-md-6">
            <h1><span class="fa fa-user"></span><span class="xn-text"></span>  <u>Integrantes</u></h1>
        </div>
        <div class="col-md-6 text-right" style="padding: 10px">
            <?php if (Integrante::getLogged()->tipo == Integrante::TIPO_ADMINISTRADOR): ?>
                <a class="btn btn-success btn-lg" href="<?php echo $this->baseUrl(); ?>/administrador/integrante/novo"><span class="glyphicon glyphicon-plus"></span>Novo</a>
            <?php endif; ?>
        </div>
    </div>

    <?php if ($this->mensagem_sucess != ""): ?>
        <div class="alert alert-success" role="alert"><strong><?php echo $this->mensagem_sucess; ?></strong></div>
    <?php endif; ?>
    <?php if ($this->mensagem_warning != ""): ?>
        <div class="alert alert-warning" role="alert"><strong><?php echo $this->mensagem_warning; ?></strong></div>
    <?php endif; ?>
    <?php if ($this->mensagem_danger != ""): ?>
        <div class="alert alert-danger" role="alert"><strong><?php echo $this->mensagem_danger; ?></strong></div>
    <?php endif; ?>



    <form  class="form-group" action="<?php echo $this->baseUrl() ?>/administrador/integrante" method="GET">
        <div class="panel panel-default" >
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-4">
                        <div class="form-group">
                            <label>Integrante</label>
                            <input name="nome" type="text" class="form-control"  placeholder="Nome do Integrante" style="text-transform: capitalize" value="<?php echo $this->params['nome'] ?>">
                        </div>
                    </div>
                    <div class="col-xs-4">
                        <div class="form-group" >
                            <label>Categoria</label>
                            <select name="categoria" class="form-control select">
                                <option value="0">[Selecione a categoria]</option>
                                <option value="<?php echo Integrante::CATEGORIA_CANTOR ?>" <?php echo $this->params['categoria'] == 1 ? 'selected' : '' ?>>Cantor</option>
                                <option value="<?php echo Integrante::CATEGORIA_MUSICO ?>" <?php echo $this->params['categoria'] == 2 ? 'selected' : '' ?>>Músico</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="row" >
                    <div class="form-group" style="text-align:  right;">
                        <button type="submit" class="btn btn-primary" ><span class="glyphicon glyphicon-filter" ></span>Filtrar</button>
                    </div>
                </div>    
            </div>
        </div>
    </form>


    <div class="panel panel-default">
        <div class="panel-heading ui-draggable-handle">
            <h3>Lista de Grupos</h3>
        </div>
        <table class="table table-hover ">
            <thead class="tabela-header">
                <tr>
                    <th>Nome</th>
                    <th>Usuário</th>
                    <th>Categoria</th>
                    <th>Status</th>
                    <th style="text-align: center">Instrumento</th>
                    <th colspan="3"></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->lista_integrantes as $integrante): ?>
                    <tr>
                        <td><strong><?php echo $integrante->nome ?></strong></td>
                        <td><strong><?php echo $integrante->usuario ?></strong></td>
                        <td><strong><?php echo $integrante->getCategoria() ?></strong></td>
                        <td><strong><?php echo $integrante->getStatus() ?></strong></td>
                        <td style="text-align: center">
                            <?php if ($integrante->IntegranteInstrumento->count() > 0): ?>
                                <div class="dropdown">
                                    <a class="fa fa-bell" style="cursor: pointer" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></a>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" >
                                        <?php foreach ($integrante->IntegranteInstrumento as $integrante_instrumento): ?>
                                            <li><strong><?php echo $integrante_instrumento->Instrumento->nome ?></strong></li>
                                            <li role="separator" class="divider"></li>
                                        <?php endforeach; ?>
                                    </ul>
                                </div> 
                            <?php endif; ?>
                        </td>

                        <?php if (Integrante::getLogged()->tipo == Integrante::TIPO_ADMINISTRADOR): ?>
                            <td><a  onclick="return confirm('Confirma o envio de dados para email do usuario ? ')" class="glyphicon glyphicon-envelope" title="Enviar dados por email" href="<?php $this->baseUrl() ?>/administrador/integrante/email?id=<?php echo $integrante->id ?>"></a></td>
                        <?php endif; ?>
                        <?php if (Integrante::getLogged()->tipo == Integrante::TIPO_ADMINISTRADOR): ?>
                            <td><a class="glyphicon glyphicon-pencil" title="Editar" href="<?php $this->baseUrl() ?>/administrador/integrante/editar?id=<?php echo $integrante->id ?>"></a></td>
                        <?php endif; ?>
                        <?php if (Integrante::getLogged()->tipo == Integrante::TIPO_ADMINISTRADOR): ?>
                            <td><a onclick="return confirm('Confirma exclusão desse integrante ? ')" class="glyphicon glyphicon-trash" title="Excluir" href="<?php $this->baseUrl() ?>/administrador/integrante/deletar?id=<?php echo $integrante->id ?>"></a></td>
                            <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>


    <?php if (isset($this->lista_integrantes)) echo $this->paginationControl($this->lista_integrantes, "All", "paginator.phtml", $this->list_params); ?>

</div>
