<?php

/**
 * DaoEscala
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $instrumento_id
 * @property integer $integrante_id
 * @property integer $culto_id
 * @property Instrumento $Instrumento
 * @property Integrante $Integrante
 * @property Culto $Culto
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class DaoEscala extends DaoGeneric
{
    public function setTableDefinition()
    {
        $this->setTableName('escala');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('instrumento_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('integrante_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('culto_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Instrumento', array(
             'local' => 'instrumento_id',
             'foreign' => 'id'));

        $this->hasOne('Integrante', array(
             'local' => 'integrante_id',
             'foreign' => 'id'));

        $this->hasOne('Culto', array(
             'local' => 'culto_id',
             'foreign' => 'id'));
    }
}