<?php

/**
 * DaoGrupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nome
 * @property string $igreja
 * @property string $responsavel
 * @property string $imagem_grupo
 * @property Doctrine_Collection $Culto
 * @property Doctrine_Collection $Instrumento
 * @property Doctrine_Collection $Integrante
 * @property Doctrine_Collection $Musica
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class DaoGrupo extends DaoGeneric
{
    public function setTableDefinition()
    {
        $this->setTableName('grupo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nome', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('igreja', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('responsavel', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('imagem_grupo', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Culto', array(
             'local' => 'id',
             'foreign' => 'grupo_id'));

        $this->hasMany('Instrumento', array(
             'local' => 'id',
             'foreign' => 'grupo_id'));

        $this->hasMany('Integrante', array(
             'local' => 'id',
             'foreign' => 'grupo_id'));

        $this->hasMany('Musica', array(
             'local' => 'id',
             'foreign' => 'grupo_id'));
    }
}