<?php

/**
 * Grupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Grupo extends DaoGrupo {

    /**
     * Retorna o Grupo Logado
     * @return \Grupo
     */
    public static function getLogged() {
        $grupo = new Grupo();
        $grupo->id = $_SESSION['grupo_id'];
        return $grupo;
    }
    
}
