<?php

/**
 * Integrante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Integrante extends DaoIntegrante {

    const TIPO_ADMINISTRADOR = 1;
    const TIPO_INTEGRANTE = 2;
    const STATUS_ATIVO = 1;
    const STATUS_INATIVO = 2;
    const CATEGORIA_CANTOR = 1;
    const CATEGORIA_MUSICO = 2;

    public function getInstrumento() {
        $result = "";
        foreach ($this->IntegranteInstrumento as $integrante_instrumentno) {
            $result .= $integrante_instrumentno->Instrumento->nome;
        }
        return $result;
    }

    public function getCategoria() {
        $categoria = "";
        switch ($this->categoria) {
            case Integrante::CATEGORIA_CANTOR:
                $categoria = 'Cantor';
                break;
            case Integrante::CATEGORIA_MUSICO:
                $categoria = 'Músico';
                break;

            default :
                $categoria = $this->categoria;
                break;
        }
        return $categoria;
    }

    public function getStatus() {
        $status = "";
        switch ($this->status) {
            case Integrante::STATUS_ATIVO:
                $status = 'Ativo';
                break;
            case Integrante::STATUS_INATIVO:
                $status = 'Inativo';
                break;

            default :
                $status = $this->status;
                break;
        }
        return $status;
    }

    public function getTipoIntegrante() {
        $tipo = "";
        switch ($this->tipo) {
            case Integrante::TIPO_ADMINISTRADOR:
                $tipo = 'Administrador';
                break;
            case Integrante::TIPO_INTEGRANTE:
                $tipo = 'Integrante';
                break;

            default :
                $tipo = $this->tipo;
                break;
        }
        return $tipo;
    }

    public static function getLogged() {
        $integrante = new Integrante();
        $integrante->nome = $_SESSION['integrante_nome'];
        $integrante->tipo = $_SESSION['integrante_tipo'];
        $integrante->categoria = $_SESSION['integrante_categoria'];
        $integrante->foto = $_SESSION['integrante_foto'];
        $integrante->id = $_SESSION['integrante_id'];

        return $integrante;
    }

}
