
<form action="" method="post" enctype="multipart/form-data">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12">
                    <div class="col-xs-4">
                        <div class="form-group">
                            <label>Nome da Música</label>
                            <input name="nome" type="text" class="form-control"  placeholder="Nome da Música" value="<?php echo $this->musica->nome ?>">
                        </div>
                    </div>

                    <div class="col-xs-4">
                        <div class="form-group">
                            <label>Nome do Artista/Banda</label>
                            <input name="artista" type="text" class="form-control"  placeholder="Artista/Banda" value="<?php echo $this->musica->artista_banda ?>">
                        </div>
                    </div>

                    <div class="col-xs-4">
                        <div class="form-group">
                            <label>Link da musica</label>
                            <input name="link" type="text" class="form-control"  placeholder="Link youtube" value="<?php echo $this->musica->link ?>">
                        </div>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="col-xs-6">
                        <div class="form-group">
                            <label for="exampleInputFile">Cifra</label>
                            <div>
                                <span><strong><?php echo $this->musica->cifra ?></strong></span>
                            </div>
                            <input name="cifra" type="file" id="exampleInputFile">                                 
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="form-group">
                            <label for="exampleInputFile">Power Point</label>
                            <div>
                                <span><strong><?php echo $this->musica->power_point ?></strong></span>
                            </div>
                            <input name="powerpoint" type="file" id="exampleInputFile">
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="form-group">
                            <label for="exampleInputFile">Arquivo Mp3</label>
                            <div>
                                <span><strong><?php echo $this->musica->arquivo_mp3 ?></strong></span>
                            </div>
                            <input name="mp3" type="file" id="exampleInputFile">                                   
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-6">
                            <label for="exampleInputFile">Letra</label>
                            <div>
                                <span><strong><?php echo $this->musica->letra ?></strong></span>
                            </div>
                            <input name="letra" type="file" id="exampleInputFile">
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="row text-right">
                    <div class="col-xs-12 ">
                        <div class="form-group" >
                            <a class="btn btn-default btn-lg" href="<?php echo $this->baseUrl() ?>/administrador/musica">Cancelar</a>
                            <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</form>
