<div class="col-md-12">

    <div class="page-title">
        <div class="col-xs-6">
            <h2><span class="fa fa-music"></span><span class="xn-text"></span>  <u>Músicas</u></h2>
        </div>
        <div class="col-md-6 text-right">
            <?php if (Integrante::getLogged()->tipo == Integrante::TIPO_ADMINISTRADOR): ?>
                <a class="btn btn-success btn-lg" href="<?php echo $this->baseUrl(); ?>/administrador/musica/novo"><span class="glyphicon glyphicon-plus"></span>Novo</a>
            <?php endif; ?> 
        </div>
    </div>

    <?php if ($this->mensagem_sucess != ""): ?>
        <div class="alert alert-success" role="alert"><?php echo $this->mensagem_sucess; ?></div>
    <?php endif; ?>
    <?php if ($this->mensagem_warning != ""): ?>
        <div class="alert alert-warning" role="alert"><?php echo $this->mensagem_warning; ?></div>
    <?php endif; ?>
    <?php if ($this->mensagem_danger != ""): ?>
        <div class="alert alert-danger" role="alert"><?php echo $this->mensagem_danger; ?></div>
    <?php endif; ?>




    <form  id="formulario"  class="form-group" action="<?php echo $this->baseUrl() ?>/administrador/musica" method="GET">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-4">
                        <div class="form-group">
                            <label>Música</label>
                            <input name="nome" type="text" class="form-control"  placeholder="Nome da Música" style="text-transform: capitalize" value="<?php echo $this->params['nome'] ?>">
                        </div>
                    </div>
                    <div class="col-xs-4">
                        <div class="form-group">
                            <label>Artista/Banda</label>
                            <input name="artista" type="text" class="form-control"  placeholder="Artista/Banda" style="text-transform: capitalize" value="<?php echo $this->params['artista'] ?>">
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="form-group" style="text-align: right;">
                        <button type="submit" class="btn btn-primary" ><span class="glyphicon glyphicon-filter"></span>Filtrar</button>
                    </div>
                </div>    
            </div>
        </div>
    </form>

    <div class="panel panel-default">
        <div class="panel-heading ui-draggable-handle">
            <h3>Lista de Músicas</h3>
        </div>
        <table class="table table-hover ">
            <thead class="tabela-header">
                <tr>
                    <th>Música</th>
                    <th>Artista/Banda</th>
                    <th>Grupo</th>
                    <th colspan="3"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->lista_musicas as $musica): ?>
                    <tr>
                        <td><strong><?php echo $musica->nome ?></strong></td>
                        <td><strong><?php echo $musica->artista_banda ?></strong></td>
                        <td><strong><?php echo $musica->Grupo->nome ?></strong></td>
                        <td><div class="dropdown">
                                <a class="glyphicon glyphicon-folder-open btn dropdown-toggle" type="button"  data-toggle="dropdown"  aria-expanded="false"></a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                    <?php if ($musica->letra != ""): ?>
                                        <li><a href="<?php echo $this->baseUrl() ?>/uploads/letra/<?php echo $musica->letra ?>" target="_blank">Arquivo Letra</a></li>
                                    <?php endif; ?>
                                    <?php if ($musica->cifra != ""): ?>
                                        <li><a href="<?php echo $this->baseUrl() ?>/uploads/cifra/<?php echo $musica->cifra ?>" target="_blank">Arquivo Cifra</a></li>
                                    <?php endif; ?>
                                    <?php if ($musica->link != ""): ?>
                                        <li><a href="<?php echo $musica->link ?>" target="_blank">Link Musica</a></li>
                                    <?php endif; ?>
                                    <li role="separator" class="divider"></li>
                                    <?php if ($musica->power_point != ""): ?>
                                        <li><a href="<?php echo $this->baseUrl() ?>/uploads/powerpoints/<?php echo $musica->power_point ?>" download >Baixar e Editar Power Point</a></li>
                                    <?php endif; ?>
                                    <?php if ($musica->cifra != ""): ?>
                                        <li><a href="<?php echo $this->baseUrl() ?>/uploads/cifra/<?php echo $musica->cifra ?>" download >Baixar e Editar Cifra</a></li>
                                    <?php endif; ?>
                                    <?php if ($musica->arquivo_mp3 != ""): ?>
                                        <li><a href="<?php echo $this->baseUrl() ?>/uploads/mp3/<?php echo $musica->arquivo_mp3 ?>" download >Baixar Música</a></li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </td>
                        <?php if (Integrante::getLogged()->tipo == Integrante::TIPO_ADMINISTRADOR): ?>
                            <td><a class="glyphicon glyphicon-pencil" href="<?php echo $this->baseUrl() ?>/administrador/musica/editar?id=<?php echo $musica->id ?>"></a></td>
                        <?php endif; ?>
                        <?php if (Integrante::getLogged()->tipo == Integrante::TIPO_ADMINISTRADOR): ?>
                            <td><a onclick="return confirm('Confirma a exclusão desta Música ? ')" class="glyphicon glyphicon-trash" href="<?php echo $this->baseUrl() ?>/administrador/musica/deletar?id=<?php echo $musica->id ?>"></a></td>
                            <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?php if (isset($this->lista_musicas)) echo $this->paginationControl($this->lista_musicas, "All", "paginator.phtml", $this->list_params); ?>

</div>

<!--<script>
    var btn = document.getElementById("btn-filtrar");
    btn.onclick = imprimirNaTela;
    
    
    function imprimirNaTela() {
        console.debug('voce clicou');
        var form = document.getElementById("formulario");
        form.style.display = "none";
        
        return false;
    }
    
</script>-->