<!DOCTYPE html>
<html lang="en">
    <head>        
        <!-- META SECTION -->
        <title>SongController | Gerenciador de Louvor</title>            
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="<?php echo $this->baseUrl() ?>/joli/favicon.ico" type="image/x-icon" />
        <!-- END META SECTION -->

        <!-- CSS INCLUDE -->        
        <link rel="stylesheet" type="text/css" id="theme" href="<?php echo $this->baseUrl() ?>/joli/css/theme-default.css"/>
        <!-- EOF CSS INCLUDE -->                                    
    </head>
    <body>
        <!-- START PAGE CONTAINER -->
        <div class="page-container">

            <!-- START PAGE SIDEBAR -->
            <div class="page-sidebar">
                <!-- START X-NAVIGATION -->
                <ul class="x-navigation">
                    <li class="xn-logo">
                        <a href="<?php echo $this->baseUrl() ?>/administrador">SongController</a>
                        <a href="#" class="x-navigation-control"></a>
                    </li>
                    <li class="xn-profile">
                        <a href="#" class="profile-mini">
                            <img src="<?php echo $this->baseUrl() ?>/uploads/fotointegrante/<?php echo Integrante::getLogged()->foto ?>" alt="Foto"/>
                        </a>
                        <div class="profile">
                            <div class="profile-image">
                                <?php if (Integrante::getLogged()->foto != ""): ?>
                                    <img width="100" height="100" src="<?php echo $this->baseUrl() ?>/uploads/fotointegrante/<?php echo Integrante::getLogged()->foto ?>" alt="Foto" class="img-circle" >
                                <?php else : ?>
                                    <img width="100" height="100" src="<?php echo $this->baseUrl() ?>/uploads/fotointegrante/default-user.jpg" alt="Foto" class="img-circle" >
                                <?php endif; ?>
                            </div>
                            <div class="profile-data">
                                <div class="profile-data-name"><strong><?php echo Integrante::getLogged()->nome ?></strong></div>
                                <div class="profile-data-title"><strong><?php echo Integrante::getLogged()->getCategoria() ?> | <?php echo Integrante::getLogged()->getTipoIntegrante() ?></strong></div>
                            </div>
                            <div class="profile-controls">
                                <a href="<?php echo $this->baseUrl() ?>/administrador/integrante/perfil?id=<?php echo Integrante::getLogged()->id ?>" class="profile-control-left"><span class="fa fa-info"></span></a>
                            </div>
                        </div>                                                                        
                    </li>
                    <li class="xn-title fa fa-list" style="text-align: center"><strong>  Menu</strong></li>

                    <li <?php echo $this->menu_ativo == 'pagina_inicial' ? ' class="active" ' : '' ?>><a href="<?php echo $this->baseUrl(); ?>/administrador"><span class="fa fa-desktop"></span><span class="xn-text"><strong>Dashboard</strong></span></a></li>
                    <li <?php echo $this->menu_ativo == 'grupo' ? ' class="active" ' : '' ?>><a href="<?php echo $this->baseUrl(); ?>/administrador/grupo"><span class="fa fa-group"></span><span class="xn-text"><strong>Grupos</strong></span></a></li>
                    <li <?php echo $this->menu_ativo == 'integrantes' ? ' class="active" ' : '' ?>><a href="<?php echo $this->baseUrl(); ?>/administrador/integrante"><span class="fa fa-user"></span><span class="xn-text"><strong>Integrantes</strong></span></a>
                    <li <?php echo $this->menu_ativo == 'musicas' ? ' class="active" ' : '' ?>><a href="<?php echo $this->baseUrl(); ?>/administrador/musica"><span class="fa fa-music"></span><span class="xn-text"><strong>Músicas</strong></span></a>
                    <li <?php echo $this->menu_ativo == 'instrumentos' ? ' class="active" ' : '' ?>><a href="<?php echo $this->baseUrl(); ?>/administrador/instrumento"><span class="fa fa-bell"></span><span class="xn-text"><strong>Instrumentos</strong></span></a>
                    <li <?php echo $this->menu_ativo == 'culto' ? ' class="active" ' : '' ?>><a href="<?php echo $this->baseUrl(); ?>/administrador/culto"><span class="fa fa-calendar"></span><span class="xn-text"><strong>Cultos</strong></span></a>
                </ul>
                <!-- END X-NAVIGATION -->
            </div>
            <!-- END PAGE SIDEBAR -->

            <!-- PAGE CONTENT -->
            <div class="page-content">

                <!-- START X-NAVIGATION VERTICAL -->
                <ul class="x-navigation x-navigation-horizontal x-navigation-panel">
                    <!-- TOGGLE NAVIGATION -->
                    <li class="xn-icon-button">
                        <a href="#" class="x-navigation-minimize"><span class="fa fa-dedent"></span></a>
                    </li>
                    <!-- END TOGGLE NAVIGATION -->
                    <!-- SIGN OUT -->
                    <li class="xn-icon-button pull-right">
                        <a href="#" class="mb-control" data-box="#mb-signout"><span class="fa fa-sign-out"></span></a>                        
                    </li> 
                    <!-- END SIGN OUT -->
                    <!-- MESSAGES -->

                    <!-- END MESSAGES -->
                    <!-- TASKS -->

                    <!-- END TASKS -->
                </ul>
                <!-- END X-NAVIGATION VERTICAL -->                     


                <?php echo $this->layout()->content; ?>

            </div>            
            <!-- END PAGE CONTENT -->
        </div>
        <!-- END PAGE CONTAINER -->

        <!-- MESSAGE BOX-->
        <div class="message-box animated fadeIn" data-sound="alert" id="mb-signout">
            <div class="mb-container">
                <div class="mb-middle">
                    <div class="mb-title"><span class="fa fa-sign-out"></span> Log <strong>Out</strong> ?</div>
                    <div class="mb-content">
                        <p>Deseja realmente fazer logout?</p>                    
                        <p>Pressione não para continuar logado e continuar trabalhando.</p>
                    </div>
                    <div class="mb-footer">
                        <div class="pull-right">
                            <a href="<?php echo $this->baseUrl() ?>/index/logout" class="btn btn-success btn-lg">Sim</a>
                            <button class="btn btn-default btn-lg mb-control-close">Não</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END MESSAGE BOX-->

        <!-- START PRELOADS -->
        <audio id="audio-alert" src="<?php echo $this->baseUrl() ?>/joli/audio/alert.mp3" preload="auto"></audio>
        <audio id="audio-fail" src="<?php echo $this->baseUrl() ?>/joli/audio/fail.mp3" preload="auto"></audio>
        <!-- END PRELOADS -->                  

        <!-- START SCRIPTS -->
        <!-- START PLUGINS -->
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/jquery/jquery.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/jquery/jquery-ui.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/bootstrap/bootstrap.min.js"></script>        
        <!-- END PLUGINS -->

        <!-- START THIS PAGE PLUGINS-->        
        <script type='text/javascript' src='<?php echo $this->baseUrl() ?>/joli/js/plugins/icheck/icheck.min.js'></script>        
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/scrolltotop/scrolltopcontrol.js"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/morris/raphael-min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/morris/morris.min.js"></script>       
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/rickshaw/d3.v3.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/rickshaw/rickshaw.min.js"></script>
        <script type='text/javascript' src='<?php echo $this->baseUrl() ?>/joli/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'></script>
        <script type='text/javascript' src='<?php echo $this->baseUrl() ?>/joli/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js'></script>                
        <script type='text/javascript' src='<?php echo $this->baseUrl() ?>/joli/js/plugins/bootstrap/bootstrap-datepicker.js'></script>                
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/owl/owl.carousel.min.js"></script>                 

        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/moment.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/daterangepicker/daterangepicker.js"></script>


        <script type='text/javascript' src='<?php echo $this->baseUrl() ?>/joli/js/plugins/icheck/icheck.min.js'></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/bootstrap/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/bootstrap/bootstrap-timepicker.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/bootstrap/bootstrap-colorpicker.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/bootstrap/bootstrap-file-input.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/bootstrap/bootstrap-select.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins/tagsinput/jquery.tagsinput.min.js"></script>
        <!-- END THIS PAGE PLUGINS-->        

        <!-- START TEMPLATE -->


        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/plugins.js"></script>        
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/actions.js"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/joli/js/demo_dashboard.js"></script>
        <!-- END TEMPLATE -->
        <!-- END SCRIPTS -->         
    </body>
</html>